#!/bin/bash

ONTOLOGY_PATH="components"

function section {
echo
echo "# -----------------------------------------------------------------------"
echo "# $1"
echo "# -----------------------------------------------------------------------"
echo
}

function create_ontology {
section "WARNING: THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT DIRECTLY"

cat $ONTOLOGY_PATH/prefix.ttl | sed -e "s/|compiledate|/$(date --iso-8601=seconds)/g" |sed -e "s/+0000/Z/g"

for f in $(ls $ONTOLOGY_PATH/*.ttl|grep -v -w "prefix.ttl"); do
section "$(basename $f)"
cat $f
done
}

create_ontology > $ONTOLOGY_PATH.ttl
python ttl2xml.py $ONTOLOGY_PATH.ttl
