#!/bin/bash

# THIS NEEDS TO BE A RELATIVE PATH
#ONTOLOGY_PATH=""

if [ "$1" ] ; then
  ONTOLOGY_PATH="$1"
fi

if [ "$ONTOLOGY_PATH" == "." ]; then
  ONTOLOGY_PATH=""
fi 

function section {
echo
echo "# -----------------------------------------------------------------------"
echo "# $1"
echo "# -----------------------------------------------------------------------"
echo
}

function create_ontology {
section "WARNING: THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT DIRECTLY"

cat $PWD/$ONTOLOGY_PATH/components/prefix.ttl | sed -e "s/|compiledate|/$(date -u +"%Y-%m-%dT%H:%M:%SZ")/g" |sed -e "s/+0000/Z/g"

for f in $(ls $PWD/$ONTOLOGY_PATH/components/*.ttl|grep -v -w "prefix.ttl"); do
section "$(basename $f)"
cat $f
done
}

create_ontology > $PWD/$ONTOLOGY_PATH/$(basename $PWD/$ONTOLOGY_PATH).ttl
python ttl2xml.py  $PWD/$ONTOLOGY_PATH/$(basename $PWD/$ONTOLOGY_PATH).ttl
python ttl2jsonld.py  $PWD/$ONTOLOGY_PATH/$(basename $PWD/$ONTOLOGY_PATH).ttl
