#!/bin/bash

# THIS NEEDS TO BE A RELATIVE PATH
#ONTOLOGY_PATH=""

if [ "$ONTOLOGY_PATH" == "." ]; then
  ONTOLOGY_PATH=""
fi 

function section {
echo
echo "# -----------------------------------------------------------------------"
echo "# $1"
echo "# -----------------------------------------------------------------------"
echo
}

function create_ontology {
section "WARNING: THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT DIRECTLY"

cat $PWD/$ONTOLOGY_PATH/components/prefix.ttl | sed -e "s/|compiledate|/$(date --iso-8601=seconds)/g" |sed -e "s/+0000/Z/g"

for f in $(ls $PWD/$ONTOLOGY_PATH/components/*.ttl|grep -v -w "prefix.ttl"); do
section "$(basename $f)"
cat $f
done
}

create_ontology > $(basename $PWD/$ONTOLOGY_PATH).ttl
python ttl2xml.py  $(basename $PWD/$ONTOLOGY_PATH).ttl
